/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bifast.process;

import java.util.HashMap;
import org.apache.log4j.Logger;
import org.jdom2.Element;
import org.jdom2.Namespace;

/**
 *
 * @author suhanda
 */
public class MessageRejectResponse {

    private static Logger log = Logger.getLogger(MessageRejectResponse.class);

    public String process() {
        String xml_nya = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<ns:BusMsg xmlns:ns2=\"urn:iso:std:iso:20022:tech:xsd:admi.002.001.01\" xmlns:ns=\"urn:iso\" \n"
                + "xmlns:ns1=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n"
                + "xsi:schemaLocation=\"urn:iso ../../../../xsd/phase1/MainCIHub.xsd \">\n"
                + "<ns:AppHdr>\n"
                + "<ns1:Fr>\n"
                + "<ns1:FIId>\n"
                + "<ns1:FinInstnId>\n"
                + "<ns1:Othr>\n"
                + "<ns1:Id>FASTIDJA</ns1:Id>\n"
                + "<!-- Sending system -->\n"
                + "</ns1:Othr>\n"
                + "</ns1:FinInstnId>\n"
                + "</ns1:FIId>\n"
                + "</ns1:Fr>\n"
                + "<ns1:To>\n"
                + "<ns1:FIId>\n"
                + "<ns1:FinInstnId>\n"
                + "<ns1:Othr>\n"
                + "<ns1:Id>INDOIDJA</ns1:Id>\n"
                + "<!-- Receiving system -->\n"
                + "</ns1:Othr>\n"
                + "</ns1:FinInstnId>\n"
                + "</ns1:FIId>\n"
                + "</ns1:To>\n"
                + "<ns1:BizMsgIdr>20210301FASTIDJA000ORB12345678</ns1:BizMsgIdr>\n"
                + "<ns1:MsgDefIdr>admi.002.001.01</ns1:MsgDefIdr>\n"
                + "<ns1:CreDt>2021-03-01T12:00:00Z</ns1:CreDt>\n"
                + "</ns:AppHdr>\n"
                + "<ns:Document>\n"
                + "<ns:MessageReject>\n"
                + "<ns2:RltdRef>\n"
                + "<ns2:Ref>20210301INDOIDJA0000000000026770339</ns2:Ref>\n"
                + "</ns2:RltdRef>\n"
                + "<ns2:Rsn>\n"
                + "<ns2:RjctgPtyRsn>0015</ns2:RjctgPtyRsn>\n"
                + "<ns2:RjctnDtTm>2021-04-09T21:21:01.896</ns2:RjctnDtTm>\n"
                + "<ns2:ErrLctn>StaxXmlSubFieldType</ns2:ErrLctn>\n"
                + "<ns2:RsnDesc>cvc-complex-type.2.4.a: Invalid content was found starting with element \n"
                + "'{\"urn:iso:std:iso:20022:tech:xsd:admn.001.001.01\":InstrId}'. One of \n"
                + "'{\"urn:iso:std:iso:20022:tech:xsd:admn.001.001.01\":FnctnCd}' is expected.</ns2:RsnDesc>\n"
                + "<ns2:AddtlData>&lt;?xml version=\"1.0\" encoding=\"utf-8\"?&gt;\n"
                + " &lt;ns:BusMsg xmlns:ns=\"urn:iso\" xmlns:ns1=\"urn:iso:std:iso:20022:tech:xsd:admn.001.001.01\" \n"
                + "xmlns:ns2=\"urn:iso:std:iso:20022:tech:xsd:head.001.001.01\"&gt;\n"
                + " &lt;ns:AppHdr&gt;\n"
                + " &lt;ns2:CharSet&gt;ABCD&lt;/ns2:CharSet&gt;\n"
                + " &lt;ns2:Fr&gt;\n"
                + " &lt;ns2:FIId&gt;\n"
                + "&lt;ns2:FinInstnId&gt;\n"
                + " &lt;ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:MmbId&gt;test&lt;/ns2:MmbId&gt;\n"
                + " &lt;/ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:Othr&gt;\n"
                + " &lt;ns2:Id&gt;NWMGSGSG&lt;/ns2:Id&gt;\n"
                + " &lt;/ns2:Othr&gt;\n"
                + " &lt;/ns2:FinInstnId&gt;\n"
                + " &lt;/ns2:FIId&gt;\n"
                + " &lt;/ns2:Fr&gt;\n"
                + " &lt;ns2:To&gt;\n"
                + " &lt;ns2:FIId&gt;\n"
                + " &lt;ns2:FinInstnId&gt;\n"
                + " &lt;ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:MmbId&gt;test&lt;/ns2:MmbId&gt;\n"
                + " &lt;/ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:Othr&gt;\n"
                + " &lt;ns2:Id&gt;CITENANT&lt;/ns2:Id&gt;\n"
                + " &lt;/ns2:Othr&gt;\n"
                + " &lt;/ns2:FinInstnId&gt;\n"
                + " &lt;/ns2:FIId&gt;\n"
                + " &lt;/ns2:To&gt;\n"
                + " &lt;ns2:BizMsgIdr&gt;20210409NWMGSGSGXXX0000000037992889&lt;/ns2:BizMsgIdr&gt;\n"
                + " &lt;ns2:MsgDefIdr&gt;'admn.001.001.01'&lt;/ns2:MsgDefIdr&gt;\n"
                + " &lt;ns2:BizSvc&gt;CI&lt;/ns2:BizSvc&gt;\n"
                + " &lt;ns2:CreDt&gt;2021-04-09T07:21:00Z&lt;/ns2:CreDt&gt;\n"
                + " &lt;ns2:CpyDplct&gt;CODU&lt;/ns2:CpyDplct&gt;\n"
                + "&lt;ns2:PssblDplct&gt;false&lt;/ns2:PssblDplct&gt;\n"
                + " &lt;ns2:Prty&gt;NORM&lt;/ns2:Prty&gt;\n"
                + " &lt;ns2:Rltd&gt;\n"
                + " &lt;ns2:Fr&gt;\n"
                + " &lt;ns2:FIId&gt;\n"
                + " &lt;ns2:FinInstnId&gt;\n"
                + " &lt;ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:MmbId&gt;test&lt;/ns2:MmbId&gt;\n"
                + " &lt;/ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:Othr&gt;\n"
                + " &lt;ns2:Id&gt;NWMGSGSG&lt;/ns2:Id&gt;\n"
                + " &lt;/ns2:Othr&gt;\n"
                + " &lt;/ns2:FinInstnId&gt;\n"
                + " &lt;/ns2:FIId&gt;\n"
                + " &lt;/ns2:Fr&gt;\n"
                + " &lt;ns2:To&gt;\n"
                + " &lt;ns2:FIId&gt;\n"
                + " &lt;ns2:FinInstnId&gt;\n"
                + " &lt;ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:MmbId&gt;test&lt;/ns2:MmbId&gt;\n"
                + " &lt;/ns2:ClrSysMmbId&gt;\n"
                + " &lt;ns2:Othr&gt;\n"
                + " &lt;ns2:Id&gt;CITENANT&lt;/ns2:Id&gt;\n"
                + " &lt;/ns2:Othr&gt;\n"
                + " &lt;/ns2:FinInstnId&gt;\n"
                + " &lt;/ns2:FIId&gt;\n"
                + " &lt;/ns2:To&gt;\n"
                + "&lt;ns2:BizMsgIdr&gt;20210409NWMGSGSGXXX0000000037992889&lt;/ns2:BizMsgIdr&gt;\n"
                + " &lt;ns2:MsgDefIdr&gt;'admn.001.001.01'&lt;/ns2:MsgDefIdr&gt;\n"
                + " &lt;ns2:CreDt&gt;2021-04-09T07:21:00Z&lt;/ns2:CreDt&gt;\n"
                + " &lt;/ns2:Rltd&gt;\n"
                + " &lt;/ns:AppHdr&gt;\n"
                + " &lt;ns:Document&gt;\n"
                + " &lt;ns:AdmnReq&gt;\n"
                + " &lt;ns1:GrpHdr&gt;\n"
                + " &lt;ns1:MsgId&gt;20210409NWMGSGSGXXX0000000026770339&lt;/ns1:MsgId&gt;\n"
                + " &lt;ns1:CreDtTm&gt;2021-04-09T07:21:00Z&lt;/ns1:CreDtTm&gt;\n"
                + " &lt;/ns1:GrpHdr&gt;\n"
                + " &lt;ns1:AdmnTxInf&gt;\n"
                + " &lt;ns1:InstrId&gt;20210409NWMGSGSGXXX0000000026770339&lt;/ns1:InstrId&gt;\n"
                + " &lt;ns1:InstgAgt&gt;\n"
                + " &lt;ns1:FinInstnId&gt;\n"
                + " &lt;ns1:Othr&gt;\n"
                + " &lt;ns1:Id&gt;NWMGSGSG&lt;/ns1:Id&gt;\n"
                + " &lt;/ns1:Othr&gt;\n"
                + " &lt;/ns1:FinInstnId&gt;\n"
                + " &lt;/ns1:InstgAgt&gt;\n"
                + " &lt;/ns1:AdmnTxInf&gt;\n"
                + " &lt;/ns:AdmnReq&gt;\n"
                + " &lt;/ns:Document&gt;\n"
                + " &lt;/ns:BusMsg&gt; </ns2:AddtlData>\n"
                + "</ns2:Rsn>\n"
                + "</ns:MessageReject>\n"
                + "</ns:Document>\n"
                + "</ns:BusMsg>";
        return xml_nya;
    }
}
